version: "3.9"

services:
  api:
    image: ghcr.io/YOUR_GH_OWNER/python-api:\
    env_file:
      - ./app.env
    networks:
      - edge
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.python-api.rule=Host(pi-APP.phamvuong.io.vn)
        - traefik.http.services.python-api.loadbalancer.server.port=8000

networks:
  edge:
    external: true
  internal:
    driver: overlay
